site_name: CDEB
site_url: https://ai-chem.github.io/CDEB/
repo_url: https://github.com/ai-chem/CDEB/
edit_uri: blob/main/docs/

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.svg
  features:
    - content.action.edit
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.path
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
    - header.autohide
    - toc.follow
  palette:
    - scheme: slate # Dark Mode
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep orange
      accent: blue
    - scheme: default # Light Mode
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: deep orange
      accent: blue

nav:
  - Home: index.md
  - Overview:
      - docs/overview/project_motivation.md
      - docs/overview/datasets_description.md
  - About:
#      - docs/about/changelog.md
#      - docs/about/conduct.md
      - docs/about/license.md

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ""
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - autorefs
  - social
  - offline
#  - gen-files:
#      scripts:
#        - docs/scripts/???.py

copyright: Copyright &copy; 2025 Center for AI in Chemistry, ITMO University
